version: "3"

services: 
    project:
        container_name: playlab-${COURSE}
        build: .
        image: playlab-${COURSE}
        stdin_open: true 
        tty: true
        privileged: true
        environment:
            - COURSE:${COURSE}
            - CURRENT_FLASK_FOLDER:${CURRENT_FLASK_FOLDER}
            - NGINX_PORT=${NGINX_PORT}
            - PORT_MAPPING=${PORT_MAPPING}
        volumes: 
            - ../projects:/workspace/projects
            - ../www/${CURRENT_FLASK_FOLDER}:/workspace/www
        expose:   
            - ${NGINX_PORT}
        ports: 
            - ${PORT_MAPPING}
        depends_on:
            - webserver # ensure that the webserver will always start first
            - db
        network_mode: "host"
    webserver:
        container_name: playlab-nginx-${COURSE}
        image: nginx:1.21.0
        restart: always
        #env_file:
        #    - .env
        environment:
            - COURSE:${COURSE}
            - NGINX_PORT=${NGINX_PORT}
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - ${NGINX_PORT}:80
    db:
        container_name: playlab-db-${COURSE}
        image: mysql/mysql-server:8.0
        restart: always
        environment:
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        ports:
            - 3306:3306
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./cnf/custome2.cnf:/etc/my.cnf
        network_mode: "host"
